### ISSUE TITLE
Why this project?

### ISSUE THREAD

**Issue by miparnisari** [outcaste-io/ristretto#10]
https://github.com/outcaste-io/ristretto/blob/a9bee0151d186b422d4d6cc23e41a08f6c21f152/README.md?plain=1#L7

Could you clarify what are the differences between both projects?

**Comment by manishrjain** [comment]
The original Dgraph team left the company in Jan 2022, and forked this project. This one is being run by me, with help from Karl, the original authors of the library. This is the library that I use in my projects.

**Comment by miparnisari** [comment]
Ok so we should not use dgraph-io/ristretto?

**Comment by manishrjain** [comment]
Datadog is using this one: https://github.com/outcaste-io/ristretto/pull/8#issuecomment-1652986233
