### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by atlas-comstock** [outcaste-io/ristretto#4]
Hi, could you release a new version?
I want to use a new version that includes https://github.com/dgraph-io/ristretto/pull/281 which already includes in your repo.

**Comment by atlas-comstock** [comment]
@karlmcguire thanks, I already forked one and released myself, but if possible, would like to use your release.

**Comment by atlas-comstock** [comment]
And if possible, could you update the issue setting?

**Comment by atlas-comstock** [comment]
@karlmcguire hi, any update?

**Comment by bothra90** [comment]
@manishrjain: Could you help with this, please?

**Comment by atlas-comstock** [comment]
hey, we already forked and released a new version: https://github.com/talariadb/ristretto/releases

**Comment by seanbachelder** [comment]
I believe a new version is also needed for this PR to go through: https://github.com/DataDog/datadog-agent/pull/12559. Any chance we can get a v0.2.0 release/tag?

**Comment by manishrjain** [comment]
Hey guys. This seemed to have slipped through. I can create a release tag.

**Comment by manishrjain** [comment]
https://github.com/outcaste-io/ristretto/releases/tag/v0.2.0

Is this sufficient? Let me know if there's anything else you need.

**Comment by seanbachelder** [comment]
Thanks @manishrjain! I think that should be enough 👍

**Comment by manishrjain** [comment]
Closing.

**Comment by seanbachelder** [comment]
@manishrjain Any ideas of why we are seeing this issue? https://github.com/DataDog/datadog-agent/pull/13630#issuecomment-1279430705

**Comment by manishrjain** [comment]
@seanbachelder -- Not quite sure why you guys are seeing that. I did the tag 0.2.0 release, I doubt I pushed it again / twice, etc.
